### ISSUE TITLE
Please consider sending bluetooth commands in parallel

### ISSUE THREAD

**Issue by Tommigun1980** [bwp91/homebridge-govee#108]
* **Please explain your feature request in a one or two sentences.**

I own a few Govee bluetooth light strips and am using your plugin to great success, so thanks so much for it!
However, the official Govee app seems to send bluetooth commands in parallel, as if I for example send a grouped request (via the "Smarts" section in the official app) it gets reflected in all of the lights at the same time, while sending even a few commands via the plugin takes an eternity as every single part of the command seems to happen in sequence with at least a 500 ms delay. This makes actions like changing style and brightness take an eternity on three strips, and any possible patterns get out of sync.

Thank you!

* **Any particular Govee devices that this relates to?**

H6127

**Comment by ThisIsNoahEvans** [comment]
Second this, although over an AWS connection with H6141. When changing HomeKit scenes on my two light strips, one changes the colour, then the brightness, then the other changes the colour, then the brightness. It's not an overly pleasant experience - I get that when sending requests over the Internet there could be delay, but it certainly feels to me like sending multiple requests at once could make this experience a little better (if possible)

**Comment by bwp91** [comment]
The plugin uses a queue to send device updates, as originally the plugin only used the API, and there was a lot of issues where sending multiple updates in quick succession would result in failures (even when govee accepted the http request). This is the reason I originally added the queue.

The plugin has to use separate requests for on/off state, brightness and colour, there is no way of sending multiple changes in one http/aws request.

Recently when I implemented the bluetooth and aws connection options, I built these 'inside' the queue. I have just released a beta version of the plugin which takes the ble and aws requests outside the queue, so that only api requests use the queue as originally intended. If anyone wants to try the beta, maybe it will speed some things up.

For devices that support AWS connection method, it might be worth setting up a govee diy scene with the brightness and colour you want, then using the plugin config to make this govee scene available in the Eve app, and creating a homekit scene from this. This would mean the plugin only needs to send one aws request (per device).

**Comment by bwp91** [comment]
These three different connection methods make it quite complex when sending updates.

- If the device supports AWS, then this command will be sent first, but the plugin does not get a response so it does not know if the command has been successful or not. AWS supports turning on/off, brightness, colour and scenes
- If the device supports BLE, the command will also be attempted this method after AWS, but BLE can be temperamental. BLE supports turning on/off, brightness and colour
- If the BLE fails or the device does not support this, then the command will be sent via API. This is the most reliable, but slowest method. But too many API requests in quick succession can also lead to issues. API only supports on/off, brightness and colour.

There is also a small delay when sending an ON/OFF command, so that if using a homekit scene, the brightness and colour commands are send **before** the on/off command. If the on/off command is sent first, then the device will turn on with the original colour and *then* turn to the new colour, which neither was an overly pleasant experience!
