### ISSUE TITLE
Support H5102

### ISSUE THREAD

**Issue by LandryTodd92** [bwp91/homebridge-govee#128]
`<!--` PLEASE READ BEFORE POSTING A NEW ISSUE
 → If you are giving feedback or requesting a new feature then feel free to ignore this template.
 → If you are experiencing an issue with the plugin then please use this template as well as you can.
 → Things that may seem unimportant to you are often helpful in finding the cause of the issue.
-->

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge with Config Ui

* Which version of Homebridge/HOOBS do you have?
4.41.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
4.14.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H5102

 [Smart Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"0D:10:A4:C1:38:89:59:3C","deviceName":"Smart Thermometer","model":"H5102","httpInfo":{"device":"0D:10:A4:C1:38:89:59:3C","sku":"H5102","spec":"","versionHard":"1.00.01","versionSoft":"1.00.04","deviceName":"Smart Thermometer","deviceExt":{"lastDeviceData":"{\"online\":false,\"tem\":2440,\"hum\":4240,\"lastTime\":1634468940000}","deviceSettings":"{\"battery\":100,\"humMax\":10000,\"temCali\":0,\"humMin\":0,\"address\":\"A4:C1:38:89:59:3C\",\"temMax\":6000,\"humCali\":0,\"temWarning\":false,\"bleName\":\"GVH5102_593C\",\"temMin\":-2000,\"humWarning\":false,\"deviceName\":\"Smart Thermometer\"}","extResources":"{\"skuUrl\":\"http://s3.amazonaws.com/govee-public/sku-img/56e8e46c92ff1eea18771cd09a77dcd0-add_list_type_device_h5102.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":8},"isAPIDevice":false}

**Comment by bwp91** [comment]
Hi @LandryTodd92 

Please install the beta version of the plugin, v4.14.1-beta.1.

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

This device should then be added to Homebridge. The plugin will use the latest data from the cloud, which may not be up to date since the device I think is only bluetooth.

You may have better luck with the homebridge-plugin-govee plugin which uses bluetooth to connect to these sensors:

https://www.npmjs.com/package/homebridge-plugin-govee

Thanks!

**Comment by LandryTodd92** [comment]
Thanks but I did get it to work thanks for the quick reply 

Landry Bertsch
