### ISSUE TITLE
H6199 Lack of support

### ISSUE THREAD

**Issue by masonjmiller** [bwp91/homebridge-govee#145]
### What issue do you have? Please be as thorough and explicit as possible.
I don't believe it's working at all with the bluetooth connection, I've successfully found the device ID, turned on device logging, enabled BLE, aside from the interval logging I can't see what mode it's changing to when I switch between video mode, diy mode, color mode, scene, etc.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
4.0.71

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
4.17.1-beta.7

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6199 Govee Immersion TV LED Backlights with Camera

### Please paste any relevant logs below.
```
Govee BridgeGovee[TV Strip] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":35,"colorTemInKelvin":5500,"colorTem":5500}].
```

**Comment by bwp91** [comment]
Hi @masonjmiller 

The accessory in the Home app will not show which mode the device is currently in. It will always show the last on/off, brightness and colour states. This is simply since there is no *nice* way of showing other modes with a homekit lightbulb accessory.

You can setup homekit scenes to enable the light to turn to different modes setup in the govee app, not sure if you have seen this wiki entry:

https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

If you don't think bluetooth is working, you can turn on plugin debug logging to see which connection method is being used. Typical commands like on/off, brightness and colour will use the bluetooth if available, but other commands like turning to different scenes may not be supported by bluetooth and other connection methods will be used instead.

I hope I have answered what you are getting at?

**Comment by masonjmiller** [comment]
Hi @bwp91, I did read that wiki entry however it appears that changing the mode of the device within Govee doesn't actually trigger anything in the logs like that entry shows. My guess is that bluetooth is the only method that supports the scene changing for this device and I simply can't get bluetooth to work with hoobs and this device, even if I add it into the Govee bridge configuration, nothing seems to work at all: https://ibb.co/NjBbvFY

`[TV Strip] initialised with id [A3:F7:D0:33:36:32:32:3E].`
`[TV Strip] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":35,"colorTemInKelvin":5500,"colorTem":5500}].`

**Comment by bwp91** [comment]
The plugin doesn't do any polling via bluetooth for the current device status/mode.

The 'codes' that trigger in the logs for different scenes are only available when using the AWS connection. They will appear when the light is connected to wifi (ie **not** connected to bluetooth on your phone) and the govee app is used to choose a different scene.

The plugin doesn't/cannot monitor bluetooth traffic between your phone and the device. The bluetooth codes are very difficult to find, I am only able to offer the fixed list on that wiki entry, found by a different user who did some reverse engineering.

I noticed that you have disabled AWS connection in the plugin settings... any reason for this?

The log entries that appear like below are from the background polling of the govee api for your device. The API data doesn't show any current modes, it only shows the last on/off, brightness and colour of the device.

```
[TV Strip] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":35,"colorTemInKelvin":5500,"colorTem":5500}].
```

Can you restart the plugin and show me all the logs that appear from the plugin initialising? If there are any issues with bluetooth hardware/software, they will appear here.

**Comment by kv1296** [comment]
Maybe I can shed some light on this issue:

When you change the mode of the H6199 in the Govee app to Video mode, it does not trigger the yellow text AWS log in the Homebridge log like the other mode changes do, instead the log records this:

`[12/9/2021, 9:26:39 PM] [Govee] [TV Backlight] [AWS] message event [{"msg":{"transaction":"v_1639103199083895","data":{"command":["MwUAAAAaAAAAAAAAAAAAAAAAACw=","qgUBAAAAAAAAAAAAAAAAAAAAAK4="]},"type":1,"cmdVersion":0,"cmd":"ptReal"}}].
[12/9/2021, 9:26:39 PM] [Govee] [TV Backlight] [AWS] receiving update [{"transaction":"v_1639103199083895","data":{"command":["MwUAAAAaAAAAAAAAAAAAAAAAACw=","qgUBAAAAAAAAAAAAAAAAAAAAAK4="]},"type":1,"cmdVersion":0,"cmd":"ptReal","source":"AWS"}].`

I tried copying and pasting the command data in the format I saw recorded in the logs in the Custom Scene box.  When the scene is run this is what appears in the logs:

`[12/9/2021, 9:30:00 PM] [Govee] [TV Backlight] [AWS] message event [{"msg":{"transaction":"y_1639103400346679","type":0,"cmdVersion":0,"cmd":"status"}}].
[12/9/2021, 9:30:02 PM] [Govee] [TV Backlight] [AWS] sending update {"msg":{"cmd":"ptReal","cmdVersion":0,"data":{"command":["MwUAAAAaAAAAAAAAAAAAAAAAACw=","qgUBAAAAAAAAAAAAAAAAAAAAAK4="]},"transaction":"v_1639103402936000","type":1}}.
[12/9/2021, 9:30:02 PM] [Govee] [TV Backlight] adaptive lighting disabled due to significant colour change.
[12/9/2021, 9:30:02 PM] [Govee] [TV Backlight] current scene [Scene].
[12/9/2021, 9:30:03 PM] [Govee] [TV Backlight] [AWS] message event [{"msg":{"cmd":"ptReal","cmdVersion":0,"data":{"command":["MwUAAAAaAAAAAAAAAAAAAAAAACw=","qgUBAAAAAAAAAAAAAAAAAAAAAK4="]},"transaction":"v_1639103402936000","type":1}}].
[12/9/2021, 9:30:03 PM] [Govee] [TV Backlight] [AWS] receiving update [{"cmd":"ptReal","cmdVersion":0,"data":{"command":["MwUAAAAaAAAAAAAAAAAAAAAAACw=","qgUBAAAAAAAAAAAAAAAAAAAAAK4="]},"transaction":"v_1639103402936000","type":1,"source":"AWS"}].
[12/9/2021, 9:30:03 PM] [Govee] [TV Backlight] not sending AWS update as command not supported via AWS.`

It seems like maybe the plugin isn't properly recording the AWS code for the Video mode. Alternatively maybe the Video mode command cannot be sent via AWS?

**Comment by bwp91** [comment]
@kv1296 what is the code you have configured for this video mode in the plugin settings?

**Comment by kv1296** [comment]
I used:

`MwUAAAAaAAAAAAAAAAAAAAAAACw=,qgUBAAAAAAAAAAAAAAAAAAAAAK4=||ptReal||`

**Comment by bwp91** [comment]
Yes, this looks correct. And when you run the scene, does the device change to video mode? It looks like the command is being sent correctly as the AWS server will "reply" with the same data that has been sent

**Comment by kv1296** [comment]
The strange thing is...it just starting working properly! Before, it was not updating to video mode. I'll let you know if it changes, great job!
