### ISSUE TITLE
Govee sensor data showing in Homebridge log but not through Homekit

### ISSUE THREAD

**Issue by jonnyquest777** [bwp91/homebridge-govee#148]
I'm new to Homebridge but not to home automation.  I added your Govee plugin to my Homebridge server and configured the plugin.  I have a temperature sensor and the sensor is reporting through your plugin Model H5053 and it pulls the data as I can see temperature reading in the Homebridge log.  But when I look on my Ipad there are not any new accessories added.  When I added a plugin for my garage doors there were several accessories automatically added.  Maybe the Govee sensor is not added as I noticed it is not supported.   I figure that I am close since the plugin is reading the data but can't figure out how to get it added on my ipad through the Home app.  Thanks and good work with the plugin.   Lee

**Comment by jonnyquest777** [comment]
I checked and the temperature and humidity are showing up in a Homebridge Accessory but not on the Apple Home app.  I'll keep looking.

**Comment by bwp91** [comment]
Hi @jonnyquest777 

The sensors don't appear as typical tiles in the home app, they appear as circles at the top of the screen with the temperature and humidity data. Since they are only sensors, there is nothing to "control" via the home app.

If you are running the plugin in a child bridge through Homebridge UI, have you added the bridge to homekit with the "+" icon in the home app?

**Comment by jonnyquest777** [comment]
Hi Ben,

I'm all good. The sensor appears as you mentioned.  I had never used a sensor with Homekit so they were there as you mentioned.  Thank you for making the plug in.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
