### ISSUE TITLE
Adding Grill Thermometers

### ISSUE THREAD

**Issue by ShaunRoberts543** [bwp91/homebridge-govee#163]
Could the grill thermometers be added as devices?  I have included the information on the two that I have from the log in Homebridge:

{"device":"E5:D8:A4:C1:38:BF:97:15","deviceName":"Oven Thermometer","model":"H5183","httpInfo":{"groupId":0,"device":"E5:D8:A4:C1:38:BF:97:15","sku":"H5183","spec":"","versionHard":"1.00.01","versionSoft":"1.03.19","deviceName":"Oven Thermometer","deviceExt":{"deviceSettings":"{\"address\":\"A4:C1:38:BF:97:15\",\"bleName\":\"GVH5183_BF9715\",\"ic\":0,\"sku\":\"H5183\",\"device\":\"E5:D8:A4:C1:38:BF:97:15\",\"deviceName\":\"Oven Thermometer\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.03.19\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":29},"isAPIDevice":false}
[17/12/2021, 14:15:04] [Govee] [Grill Thermometer] is not currently supported, do create a Github issue with the following info:
{"device":"5E:81:C6:31:30:30:04:5B","deviceName":"Grill Thermometer","model":"H5198","httpInfo":{"groupId":0,"device":"5E:81:C6:31:30:30:04:5B","sku":"H5198","spec":"","versionHard":"3.02.02","versionSoft":"1.00.11","deviceName":"Grill Thermometer","deviceExt":{"deviceSettings":"{\"wifiName\":\"SUSA\",\"address\":\"C6:31:30:30:04:5B\",\"bleName\":\"GVH5198_30045B\",\"topic\":\"GD/4e639d939a43738d635344106bdc8c58\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"2.00.16\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"BlsEMDAxxgA=\",\"sku\":\"H5198\",\"device\":\"5E:81:C6:31:30:30:04:5B\",\"deviceName\":\"Grill Thermometer\",\"versionHard\":\"3.02.02\",\"versionSoft\":\"1.00.11\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/86609e7abca785e37937f654675b881a-add_list_type_device_5198.png\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":85},"isAPIDevice":false}

It would be great if nothing else we could use a temp being hit to trigger something like a light changing color, or a sound from a HomePod.

**Comment by bwp91** [comment]
Hi @ShaunRoberts543 

This plugin does not use bluetooth to connect to thermometers since there is already a plugin that does this. Have you checked out [homebridge-plugin-govee](https://github.com/asednev/homebridge-plugin-govee) to see if either of your H5183 or H5198 work with this plugin?

I have noticed that your H5198 also includes a `"topic"` in its data, so there is a chance that I could support this (using AWS over wifi rather than bluetooth).

Could we message on Discord about this? I would need to add some extra logging to the plugin to see if the current temperature is sent via this method?

https://discord.gg/cMGhNtZ3tW

Thanks!
