### ISSUE TITLE
H5174 Thermometer Hygrometer not updating/refreshing

### ISSUE THREAD

**Issue by tjb1013** [bwp91/homebridge-govee#164]
### What issue do you have? Please be as thorough and explicit as possible.

H5174 Thermometer Hygrometer not updating/refreshing - seems to reflect the initial temperature on install.

Temperature refresh works with Homebridge Govee Thermometer Hygrometer (homebridge-plugin-govee v1.1.4)

### Details of your setup.
Homebridge v1.3.8 (HAP v0.9.7) (Homebridge 9601)
Raspbian GNU/Linux Buster (10)

Node.js v14.18.2
NPM v6.14.15

homebridge-govee v4.20.0

### Please paste any relevant logs below.

```
discovered a4c138cb1bd1 a4c138cb1bd1 a4:c1:38:cb:1b:d1 disconnected -56
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f48575075f2ffc2]

```

**Comment by bwp91** [comment]
Hi @tjb1013 

Yes, this plugin uses temperature and humidity values from the cloud. For the sensors models that support wifi, the temperature and humidity values update on a regular basis. However for the bluetooth-only models (like yours) the data will only refresh I think when you open the govee app to retrieve the data from the device.

This is why I recommend the other homebridge-plugin-govee for the bluetooth-only sensors.

My advice would be to continue using both plugins, and using the configuration to hide the sensor that **this** plugin creates, so you only have the sensor showing created by the other plugin.

You can hide the sensor from this plugin by creating an entry in the "Thermo Sensor Devices" with the device id as shown in the homebridge log, and ticking the "Hide From HomeKit" box.

I have a note about this in the "Supported Devices" wiki page:
https://github.com/bwp91/homebridge-govee/wiki/Supported-Devices#thermo-hygrometer-sensors-wi-fi

I have not introduced bluetooth scanning for sensor devices into this plugin since I haven't wanted to step into what the other plugin does and does well.

**Comment by tjb1013** [comment]
Thanks .... You had recommended the other plugin to me (and thanks). I somehow thought your latest update was providing similar support and only meant to help. Missed the note, appreciate the response.

**Comment by bwp91** [comment]
Yes, I know it seems a bit counter-intuitive in the changelogs saying a device is supported... but it isn't really supported.

I have thought about totally removing these sensors from this plugin, for simplicity, but have been unsure about actually making the change.

**Comment by tjb1013** [comment]
Interesting - can't turn off debug logging for the sensor after hiding from HomeKit... Even after deleting the device from the plugin.

--- Added ---
Re-added the device, no change (still logging). Set to "Disable all logging", still debug logging.

**Comment by bwp91** [comment]
My plugin doesn't log like this

```
discovered a4c138cb1bd1 a4c138cb1bd1 a4:c1:38:cb:1b:d1 disconnected -56
invalid peripheral, manufacturerData=[4c000215494e54454c4c495f524f434b535f48575075f2ffc2]
```

Are you sure it isnt the other plugin?

**Comment by tjb1013** [comment]
D'oh - that was it. I can't remember turning that debug on. Sorry about that.

A couple of decades ago, I headed up a company Help Desk. I have turned into one of those callers. Thanks for your patience. :)

**Comment by bwp91** [comment]
I assumed you were just testing/checking my knowledge of this plugin 😆
