### ISSUE TITLE
H6005

### ISSUE THREAD

**Issue by nateanaoki** [bwp91/homebridge-govee#171]
I haven't seen anywhere that explicitly says if H6005 can be supported. Is this a bluetooth issue or an issue with the particular model?

<img width="1260" alt="HOOBS" src="https://user-images.githubusercontent.com/22382353/147792034-2a788b13-efa4-4b5c-a2be-4ee9a0d1e113.png">

**Comment by bwp91** [comment]
Hi @nateanaoki 

> Is this a bluetooth issue or an issue with the particular model?

Neither, it's just that no-one has requested support for this model before! Can definitely give it a go.

I notice that you have blurred some of the address parts out, can you confirm if the `address` at the beginning of the fifth line down corresponds with the final six parts of the `device` on the second line down? Eg if `address` was `12:56:34:12:56:34` then is device something line `AB:CD:12:56:34:12:56:34`?

**Comment by nateanaoki** [comment]
Yes can confirm! Thanks for looking into it Ben!

**Comment by bwp91** [comment]
If you install the beta version of the plugin:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

And then since this is a bluetooth only device you will have to configure the device in the config and also you *may* have to install some extra packages on your system, more details here:
https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control

Best thing to do is check the homebridge logs as the plugin starts to see if any problems are shown.

**Comment by bwp91** [comment]
Let me know how you get on with this! I’m interested because a user could not get the `H6001` to work so I don’t know about the `H6005`, whether there is something about the `H600X` range that is different

**Comment by nateanaoki** [comment]
Hey Ben! Got it working! I think the HOOBS Pi I have is too far away so I'm going to have to move it around a bit but I was able to get the On/Off going!

**Comment by bwp91** [comment]
Ah fab. see you got on/off working, did brightness and colour work? 
for devices further away from your hoobs box would definitely recommend the govee wifi models!

**Comment by bwp91** [comment]
bluetooth can temperamental at best. unfortunately that’s the trouble with the bluetooth only devices. but in _most_ cases it works well

**Comment by pedasmith** [comment]
FYI: for the H6005, the color setting is a little different from many other bulbs. Most bulbs (and this code, as of 2025-0-05) send a 0x33 0x05 0x02 RR GG BB ... to set the colors. But the H6005 uses a 0x0D instead of the 0x02.

See [JonahClarsen](https://github.com/jonahclarsen/bluetooth_lights_controller/blob/main/bluetooth_lights_controller/bluetooth_led.py) at about line 31. There's a MANUAL = 0x02 for most bulbs, but a special MANUAL_H6005 = 0x0D for the 6005.

I haven't run your code; this was discovered by code inspection (I'm updating my own app to support this bulb)
