### ISSUE TITLE
RGBIC models Single controllable sections?

### ISSUE THREAD

**Issue by iceweasel1** [bwp91/homebridge-govee#177]
Hey Ben,

we have already communicated. On the topic of Meroos for Homebridge here on your GitHub. It's a small world. Nice that you are also doing Govee for Homebridge.

One question about a Bluetooth model. You have that on the list and state that you can control the on/off state, brightness and color for the following Govee RGB strips/bulbs here.

The model that only has Bluetooth, where I am currently considering buying or not, is the H617C model. Fortunately, that is on your list. This is an RGBIC band that makes single controllable sections possible.

Here's my question: Is this also possible via your Homebridge plugin that I can then also select individual sections in HomeKit. For example, with automations or the like.

Generally, only the RGBIC bands can do that. So both the Bluetooth model or the WLAN models, which otherwise make individual sections controllable on a band with the Govee app or Alexa.

Quite stupid question: In the Bluetooth model, how can Homebridge communicate with the LED band? With WLAN I would understand that this would go without problems.

Sorry for the questions. ;-)

Thanks
René

**Comment by bwp91** [comment]
Hi @iceweasel1 

> Here's my question: Is this also possible via your Homebridge plugin that I can then also select individual sections in HomeKit. For example, with automations or the like.
> Generally, only the RGBIC bands can do that. So both the Bluetooth model or the WLAN models, which otherwise make individual sections controllable on a band with the Govee app or Alexa.

The plugin only allows to change the colour of the complete strip. There is simply no user-interface possible within the Home app to allow for changing the colour of different sections of the strip.

The plugin, however, **can** mimic scenes and colour-segment-setups that you have already setup in the Govee app. This is done by finding a particular code that is used for the scene in question. More information about these codes can be seen here:
https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

For bluetooth-only models, this code can be difficult to determine, unless you are confident with sniffing traffic between an android phone that you (may) have and the device. Otherwise I would recommend a wi-fi model as the AWS codes can be 'sniffed' by the plugin and shown in the log. You could also use a wifi+bluetooth model.

> Quite stupid question: In the Bluetooth model, how can Homebridge communicate with the LED band? With WLAN I would understand that this would go without problems.

The plugin uses the bluetooth module from the hardware where homebridge is installed. This works best on a raspberry pi. Obviously this would not work on very old raspberry pi models which don't have bluetooth. The bluetooth connectivity doesn't currently work on newer versions of macOS, and also, since I don't have a windows machine I have been unable to test how the bluetooth works on windows.

I hope I have answered your questions, let me know if you'd like me to clarify anything else.
