### ISSUE TITLE
Add H5179 (Thermometer) to HB

### ISSUE THREAD

**Issue by naiz0** [bwp91/homebridge-govee#197]
Hi!
i tried to get the device ID from my Thermometer. The official API just give me back the information for my LED Stripes.
So i contacted the Support and they told me, that the H5179 has no API Support.

So how you guys add this device to HB? How you got the device ID?

Thank you in advance.

**Comment by bwp91** [comment]
Hi @naiz0 

~~This plugin doesn't support bluetooth-only temperature sensors, since there is already another plugin that does. You don't need the device ID since the other plugin will auto scan and setup any bluetooth-only govee sensors that it finds.~~

~~https://github.com/asednev/homebridge-plugin-govee~~

~~The H5179 is in the supported list for this plugin!~~

**Comment by naiz0** [comment]
Hi @bwp91 
This device has WiFi and BT. It is successfully connected to my WiFi Router.
It is also in you "Supported Device" list.

**Comment by bwp91** [comment]
Ah, apologies yes I am getting mixed up with all the different models 😆

Have you added your govee username and password to the configuration?

**Comment by bwp91** [comment]
The official govee API doesn't support this device so the API token is not needed.

For these devices that aren't supported by the API, the plugin uses the govee username and password to login and obtain a device list and device state.

All your devices and their device IDs should be listed in the homebridge log when the plugin starts up.

**Comment by naiz0** [comment]
yeah, for sure. 
oh dear. i had a typo in the email address. 
it works now. 
that's embarrassing

thank you very much for helping me.

**Comment by bwp91** [comment]
Happens to all of us!
Glad it's working, and thank you!
