### ISSUE TITLE
Issues with brightness H6182-F1B9

### ISSUE THREAD

**Issue by djzemp** [bwp91/homebridge-govee#32]
### What issue do you have? Please be as thorough and explicit as possible.
Changing brightness fails on most attempts.  The homebridge logs seem to return current state as altered, but the brightness doesn’t change.  Color changes also fail, but much less often.  Sometimes color changes fail, other times the change is delayed by 10’s of seconds.

I can’t always reproduce it, but the control of brightness and on/off seems to get worse after I change the color.  See log below.  After changing color, the brightness and off failed.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge with config-UI

![558F834D-C4D3-4F2D-85CC-53C8A179C3D3](https://user-images.githubusercontent.com/34108887/104148955-a778b080-5391-11eb-959b-7e8a50102865.jpeg)

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.1.7
UI 4.36.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
2.6.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6182-F1B9

### Please paste any relevant logs below.

#
```

```

**Comment by bwp91** [comment]
Hi @djzemp 
It's extremely difficult for me to identify what could be going wrong, as according to your logs everything is working well. If there were any errors being reported back by Govee then these would appear in the logs.
Does your Govee device have a stable wifi connection?

**Comment by djzemp** [comment]
I agree, it would be very difficult given those logs.  I have enabled debug
in both the Homebridge, UI, and in the Govee plugin.  Do you know how I can
enable additional logging detail?

Generally, though, my network is rather stable.  I'm not having problems
with other services including Nest products.  I have a mesh network with
excessive coverage.  And I have not had internet issues with other services.

I am somewhat new to home automation.  But very technically oriented.  Any
thoughts on how I can identify if a stable connection?  Maybe logs from my
mesh router showing connects/disconnects?  But that would only indicate
local problems.  Any way to identify connectivity issues
to Govee services?

**Comment by bwp91** [comment]
The best way to check the plugin is working properly would be to compare values with the Govee app.
This is since the plugin doesn’t “talk” to the devices directly, it interacts with the Govee servers which then would send a message down to the govee app and device.
It looks like you already have plugin debug mode on, even with this off the plugin would show any errors given by Govee. So the communication between the plugin and Govee seems okay.

But to check, for example, if you set a specific brightness % from the home app, does this value appear from the Govee app? I’m not sure if the govee app updates in real time so you might need to force close the app and reopen it.

With colour, i _think_ it doesn’t show the current colour if you select a specific colour through home app. But colour is much easier to visibly see from the device. It’s easier to check with “extreme” differences like from green to blue to red, etc.

Please also note that due to colour conversions and device capabilities, sometimes the colours more inside the colour wheel can appear slightly different in real life. With the model I own, sometimes the whiter colours can appear more orange.
