### ISSUE TITLE
plugin makes huge amount of calls to internet

### ISSUE THREAD

**Issue by phyte22** [bwp91/homebridge-govee#417]
Hi, i recently installed a pihole and found out that the most calls on my network goes to developer-api.govee.com and app2.govee.com are you aware of that? is it possible to stop that? 
Thanks! 
![image](https://user-images.githubusercontent.com/18696598/211162015-27dc646b-6888-4dfc-9d72-a396f5635985.png)

**Comment by bwp91** [comment]
Hi, if you have your username and password in the plugin config then you can remove the api key. this will stop calls to the first entry.

This is due to polling, for the second entry you could use the config to increase the polling time (so less calls), the plugin will poll differently depending on which device types you have

**Comment by phyte22** [comment]
removing the API key helped! Thank you 🙏 
I also increased the polling rate in the Advanced Settings at all 3 places to 60 (seconds). 
Will se how it goes! :)
