### ISSUE TITLE
Sync process failed as Request failed with status code 502 at createError

### ISSUE THREAD

**Issue by fairm010** [bwp91/homebridge-govee#45]
### What issue do you have? Please be as thorough and explicit as possible.

Receiving "Sync process failed as Request failed with status code 502 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15)." since upgrading plugin to v2.9.0. All features work that I can tell but laggier than before.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
HomeBridge + Config UI X

* Which version of Homebridge/HOOBS do you have?
V1.1.17

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Pi 3 Node.js v14.15.4 NPM 6.14.10

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version? 2.9.0, Yes since upgrading

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6159 RGB LED Strip

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @fairm010 

Are you getting this 502 error regularly?

**Comment by fairm010** [comment]
No not very frequently. I reloaded HomeBridge when this error occured to see if it errors again on reload but it doesnt. It generally comes back a few hours after reloading. I'll paste a log with timestamps when it appears again

**Comment by bwp91** [comment]
The 502 error would suggest to me temporary issues with the Govee server.

If the plugin receives this error (or any connection error) with Govee, it will print the error to the logs (but the plugin will not cease to function, so a Homebridge restart isn't necessary). It will continue to run this sync interval each time displaying any error until the connection problems have gone.

**Comment by fairm010** [comment]
Thanks @bwp91

**Comment by bwp91** [comment]
> All features work that I can tell but laggier than before.

You're correct in this. The plugin will now send a device update no less than 7.5 seconds from the previous. I (and other users) have been experiencing problems when two updates to Govee were sent in quick succession, Govee seemed to 'ignore' the second update unless it was 7.5 seconds later than the first.

So this is why if a device's characteristics (on/off, brightness, colour) are changed in quick succession the plugin will add these updates to a queue and send them one by one with time. 

For me this is a _very_ unfortunate, but necessary delay, otherwise updates seem to get 'lost' even though Govee reported them as accepted 😕
