### ISSUE TITLE
Request Scenes be exposed to HA

### ISSUE THREAD

**Issue by guarddog13** [bwp91/homebridge-govee#462]
* **Please explain your feature request in a one or two sentences.**
Is there any way to expose these scenes to Home Assistant or even Home Bridge. 

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Govee devices that this relates to?**
H7021

* **Anything else?**

**Comment by bwp91** [comment]
this is something i am very slowly working on 🙂

**Comment by bwp91** [comment]
Hi @guarddog13 (and @jaidon + @tmeuze - tagging as I saw you reacted to post)

In the newest beta version, I have just added an option to show a scene as an extra button in the Home app rather than in the Eve app. Here you should select 'Accessory Switch'.
<img width="292" alt="Screenshot 2023-04-30 at 13 38 32" src="https://user-images.githubusercontent.com/43026681/235353470-ee5f8ef9-c9e9-4009-828a-7f134bb8fb01.png">

This should let the switch be visible somehow in the home assistant user interface?? Please let me know on this one as I have never used HA.

A couple of notes about scenes in the new version (sorry, a template reply here:)

---

I was hoping you would be able to test a new method for obtaining scene codes I have implemented in the beta version of the plugin. It requires a bit more involvement but hopefully will result in it working properly.

- First please update to the beta version of the plugin (9.0.0-beta.0)
  - https://github.com/bwp91/homebridge-govee/wiki/Beta-Version
- Then follow the first section of this *updated* wiki page to setup and grab the proper codes
  - https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes

**Comment by jaidon** [comment]
Instantly became a scene in HomeAssistant as soon as I switched the setting in HomeBridge and restarted, and now also works with the new scene code settings as well. Thank you!!

**Comment by real-Stario** [comment]
Hey cannot find the settings in the configuration tab via Hoobs under Light Devices. Just showing "Scene for EVE App" as Standard, no Dropdown Menu. Please tell me what I am doing wrong.. but be patient :-D

**Comment by tmeuze** [comment]
@bwp91 So sorry - I just saw this. Thanks so much!

@real-Stario I just tried HOOBS a few days ago, and found that it lacked a plugin configuration UI - at least for certain ones I've tried. Might this be your issue? I have since switched to [Homebridge UI](https://github.com/homebridge/homebridge-config-ui-x).
