### ISSUE TITLE
HOOBS Box / unable to update from Node 16 / Ability to update Govee plugin past version 9.x

### ISSUE THREAD

**Issue by CadLiara** [bwp91/homebridge-govee#643]
I have a HOOBS box (non-pro) and have a question specific to this plugin.

Now I have tried getting answers from HOOBS via their direct tech support, social media and otherwise and to say their customer support is underwhelming is being generous.

The issue is that I cannot update Node JS to 18 or 20 and as such, I cannot update the plugin to version 10 or beyond. 

So my main question is, despite it being unsupported on node version 16.x, what would happen if I did update the plugin to 10.x?

What makes this even more "fun" is that trying to do ANY update on HOOBS requires the plugin to also be updated which would push it to version 10.x with NodeJS still remaining at 16.

I have always appreciated Ben's work on this plugin and that's why I am a patreon supporter, but if HOOBS can't be updated, I may be stuck with this for the foreseeable future as HOOBS support barely even responds, much less understands the issue/offers useful help.

Thank you for any help you can provide.

**Comment by claudiomorabito** [comment]
hello, I don't know if the information I'm going to provide could be useful to you and to the developer, by the way I've updated the plugin to the 10.x version on my hoobs (non pro) box with Node 16.20 and, so far, it's working flawlessly.

**Comment by CadLiara** [comment]
> hello, I don't know if the information I'm going to provide could be useful to you and to the developer, by the way I've updated the plugin to the 10.x version on my hoobs (non pro) box with Node 16.20 and, so far, it's working flawlessly.

Thank you, that is helpful as I have scoured the net and so far haven't found anything on folks using 10+ versions of the plugin with Node 16. I guessed it might be "fine" but it could run into problems down the line as the app is being developed further with Node JS versions 18+ in mind. 

It is just unfortunate that HOOBS has fallen off a cliff in terms of customer support and up to date development.

**Comment by bwp91** [comment]
I keep my plugins in line with the Homebridge node-supported versions. The warnings are for two reasons:

- admittedly, for the sake of it, in case I end up using a feature of node 18 that isnt supported in 16
- to highlight to homebridge users in general about the node versioning (since plugins are updated much more than homebridge itself

Having said this - right now there is no reason why the plugin in the latest version would not work with node 16. And this should be the case for the foreseeable future. I would always add in the release notes (even if it were a patch release) if the plugin would absolutely break on a lower version of node). Im not sure how _visible_ the release notes are in hoobs.

But for now you will be good to update and keep updated :)

**Comment by CadLiara** [comment]
Thank you Ben,
I updated and no issues.
