### ISSUE TITLE
Device cannot currently be controlled error for H6104

### ISSUE THREAD

**Issue by geekseanlin** [bwp91/homebridge-govee#65]
I am on Homebridge + config-UI using v1.3.4.
I can successfully installed the plugin and my LED (H6104) is detected and setup by both homebridge and Home app.
But whenever I use my home app to switch on the light, it shows following error -

[Govee] [Living Room TV LED] could not be updated as device cannot currently be controlled at deviceLightColour.internalOnOffUpdate (/homebridge/node_modules/homebridge-govee/lib/device/light-colour.js:109:17)

I am on node 14.16 and nom 6.14

**Comment by bwp91** [comment]
Hi @geekseanlin 

This is normally due to the device not being connected to wifi, could this be?
You can check via the Govee app, if you see this red (!) icon then the device isn't connected to wifi.

<img width="400" alt="Screenshot 2021-04-14 at 12 01 47" src="https://user-images.githubusercontent.com/43026681/114700333-4efed980-9d19-11eb-814b-62b95ac4c68e.png">

If the device really **is** connected to wifi, please try restarting homebridge (or the govee child-bridge if you use one) and let me know if you still get the error.

Thanks

**Comment by geekseanlin** [comment]
My device is both connected to wifi and Bluetooth. I enabled "Force Update" in the option and seems to be working now.
But under "Devices", showing Device Status - Offline, Retrievable - No and Controllable - Yes

**Comment by bwp91** [comment]
> Device Status - Offline, Retrievable - No and Controllable - Yes

These are three statuses per device that are provided by the Govee API and are displayed in the plugin-ui just for informative purposes.

It has occurred to me that some users' devices are being incorrectly reported as offline (for instance in your case) which is why I added the 'force updates' option. This makes the plugin skip checking whether the 'Device Status - Offline' is online.

I have no idea what is causing these incorrect statuses by Govee. Whether it's certain user network setups (site filtering, firewalls, etc) or an issue with the Govee API (probably the latter to be honest 😅)

**Comment by sidjohn1** [comment]
Looks like i had the same issue since updating to 3.x. I confirmed 2.14.2 worked fine w/o force updates turned on and every version of 3.x requires force updates to be turned on to get the lights to work. So it could be a new bug introduced in 3.x updates...

**Comment by bwp91** [comment]
> Looks like i had the same issue since updating to 3.x. I confirmed 2.14.2 worked fine w/o force updates turned on and every version of 3.x requires force updates to be turned on to get the lights to work. So it could be a new bug introduced in 3.x updates...

It's not so much a 'bug' that has been introduced. v3 of the plugin is more thorough in checking whether the device is online to be able to receive commands from the plugin. This solved the issue of a number of users wondering why their device wasn't updating as it was in fact offline.

However, it seems that in a few cases, Govee is reporting devices offline when they are actually online. So the `forceUpdates` skips the check of whether the device has been reported offline.

**Comment by RaduMC** [comment]
I'm one of the users affected, and coincidence or not, my device is also H6104.
Is there any way we could do a simple test to prove the API status is wrong? Perhaps then we could report the issue to Govee.

**Comment by bwp91** [comment]
You can turn on plugin debug logging and every 15 seconds or so you'll see an entry like this:

```
[18/04/2021, 18:12:43] [Govee] [Device Name] received update [{"online":"true","powerState":"off","brightness":47,"color":{"r":255,"b":136,"g":190}}].
```


It's the `"online":"true"` section that the plugin uses to determine if the device is online. If it's not then it will say `"online":"false"` or `"online":false`
