### ISSUE TITLE
v.3.1.3 break Home app & Siri functionality 

### ISSUE THREAD

**Issue by asimplecreature** [bwp91/homebridge-govee#71]
## What issue do you have? Please be as thorough and explicit as possible.
My H61411A1 lightstrip has stopped working since updating to v.3.1.3. After updating if I try to turn them on via Home app via my iPhone and it says they are on, but it's like the signal isn't being sent to the lightstrip. I have to use the manufacture's app to use them. Since downgrading back to previous version, all issues have disappeared and using Siri or the Home app works flawlessly again. 

I checked the logs but could not find anything that stuck out as to why it was not working. It seemed to me as if it was running properly, but something is causing the communication between Homebridge and the lightstrip.

## Details of setup

* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
Homebridge + config-ui

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 
Node.js: v14.16.1
NPM: v6.14.12

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Downgraded back to v3.1.2. v.3.1.3 breaks all Home app and Siri compatibility. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H61411A1

## Please paste any relevant logs below.

```
N/A 
```

**Comment by bwp91** [comment]
Hi @asimplecreature 

Have you tried updating to the newer version again? 

This is tricky to find the issue here as nothing has changed with regards to turning devices on and off between the two versions.

My gut feeling here is that there just happened to be a wifi connectivity issue with your device at the same time you updated.

This is why it would be good to see if updating again makes this work.

Unfortunately there are sometimes issues between the govee api server and devices (this happens in all versions of the plugin), where when the plugin sends an update, govee will report a successful message back, but the actual device isn’t updated (perhaps due to being disconnected from wifi even for that brief moment).

So please try updating again, let me know if it works.

The only difference between the two versions is how **colour** is sent to some devices.

Thanks

**Comment by asimplecreature** [comment]
No I have not, but I was going to update it again and then keep an eye on the logs to see if there was anything that seemed off. I even thought it odd that this update was just a color update so I was surprised it stopped working since updating. Will update today and report back.

**Comment by asimplecreature** [comment]
Update worked beautifully. You were right. Seems like it just didn't update right that first time. Will take note for future if this ever happens again.
